###
POST http://localhost:8080/user/add?userId=2&userName=huangjie
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/user/add?userId=1&userName=cxk
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/user/list